# Generated by Django 5.1.7 on 2025-04-01 20:50

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Permissions',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.CharField(default=None, max_length=200)),
                ('destination_id', models.CharField(default=None, max_length=36)),
            ],
            options={
                'db_table': 'Traveler_permissions',
            },
        ),
        migrations.CreateModel(
            name='TravelDestination',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('name', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'Traveler_travel_destination',
            },
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('email', models.EmailField(max_length=255, unique=True, verbose_name='email address')),
                ('display_name', models.CharField(max_length=100, unique=True)),
                ('is_active', models.BooleanField(default=True)),
                ('is_admin', models.BooleanField(default=False)),
            ],
            options={
                'db_table': 'Traveler_user',
            },
        ),
        migrations.CreateModel(
            name='TravelEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('type', models.CharField(choices=[('food_drink', 'Food & Drink'), ('shopping', 'Shopping'), ('activity', 'Activity'), ('sightseeing', 'Sightseeing'), ('other', 'Other')], default='other', max_length=100)),
                ('location', models.CharField(max_length=100)),
                ('notes', models.TextField()),
                ('destination', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Traveler.traveldestination')),
                ('contributor', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, to_field='display_name')),
            ],
            options={
                'db_table': 'Traveler_travel_entry',
            },
        ),
        migrations.AddField(
            model_name='traveldestination',
            name='created_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='travel_destinations', to=settings.AUTH_USER_MODEL),
        ),
    ]
