# Generated by Django 5.1.7 on 2025-04-11 06:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Traveler', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='travelentry',
            name='date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
