# Generated by Django 5.1.7 on 2025-04-11 20:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Traveler', '0002_travelentry_date'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='display_name',
            new_name='username',
        ),
    ]
