# Generated by Django 5.1.7 on 2025-04-14 03:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Traveler', '0003_rename_display_name_user_username'),
    ]

    operations = [
        migrations.AlterField(
            model_name='travelentry',
            name='location',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='travelentry',
            name='notes',
            field=models.TextField(blank=True),
        ),
    ]
