# Generated by Django 5.1.7 on 2025-04-25 05:24

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Traveler', '0004_alter_travelentry_location_alter_travelentry_notes'),
    ]

    operations = [
        migrations.AlterField(
            model_name='travelentry',
            name='contributor',
            field=models.ForeignKey(db_constraint=False, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, to_field='username'),
        ),
        migrations.AlterField(
            model_name='travelentry',
            name='type',
            field=models.CharField(choices=[('Food & Drink', 'Food & Drink'), ('Shopping', 'Shopping'), ('Activity', 'Activity'), ('Sightseeing', 'Sightseeing'), ('Other', 'Other')], default='Other', max_length=100),
        ),
    ]
