# Generated by Django 5.1.7 on 2025-04-25 07:13

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Traveler', '0005_alter_travelentry_contributor_alter_travelentry_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='travelentry',
            name='contributor',
            field=models.ForeignKey(db_constraint=False, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, to_field='username'),
        ),
    ]
