# Generated by Django 5.1.7 on 2026-06-06 19:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Traveler', '0008_destinationinvite'),
    ]

    operations = [
        migrations.AddField(
            model_name='travelentry',
            name='sort_order',
            field=models.IntegerField(default=0),
        ),
    ]
